"""add_session_id_to_alerts

Revision ID: 778249288549
Revises: 
Create Date: 2026-06-30 16:08:34.838044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778249288549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('total_visitors', sa.Integer(), nullable=True),
    sa.Column('unique_customers', sa.Integer(), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('suspicious_events', sa.Integer(), nullable=True),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('critical_alerts', sa.Integer(), nullable=True),
    sa.Column('avg_suspicion_score', sa.Float(), nullable=True),
    sa.Column('peak_hour', sa.Integer(), nullable=True),
    sa.Column('busiest_zone', sa.String(), nullable=True),
    sa.Column('top_incidents', sa.JSON(), nullable=True),
    sa.Column('risk_time_windows', sa.JSON(), nullable=True),
    sa.Column('most_targeted_areas', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=True)

    op.create_table('persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dominant_color', sa.String(), nullable=True),
    sa.Column('color_histogram', sa.Text(), nullable=True),
    sa.Column('appearance_embedding', sa.Text(), nullable=True),
    sa.Column('body_shape_descriptor', sa.String(), nullable=True),
    sa.Column('person_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_suspicion_score', sa.Float(), nullable=True),
    sa.Column('max_suspicion_score', sa.Float(), nullable=True),
    sa.Column('suspicion_level', sa.String(), nullable=True),
    sa.Column('appearance_cluster_id', sa.String(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('first_camera_id', sa.Integer(), nullable=True),
    sa.Column('last_camera_id', sa.Integer(), nullable=True),
    sa.Column('cameras_seen', sa.JSON(), nullable=True),
    sa.Column('last_x', sa.Float(), nullable=True),
    sa.Column('last_y', sa.Float(), nullable=True),
    sa.Column('last_bbox', sa.JSON(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_appearance_cluster_id'), ['appearance_cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_session_id'), ['session_id'], unique=True)

    op.create_table('repeat_visitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('avg_suspicion_score', sa.Float(), nullable=True),
    sa.Column('max_suspicion_score', sa.Float(), nullable=True),
    sa.Column('is_flagged_pattern', sa.Boolean(), nullable=True),
    sa.Column('dominant_color', sa.String(), nullable=True),
    sa.Column('appearance_summary', sa.JSON(), nullable=True),
    sa.Column('avg_dwell_minutes', sa.Float(), nullable=True),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('behavior_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repeat_visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repeat_visitors_cluster_id'), ['cluster_id'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('suspicion_score', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('clip_path', sa.String(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('event_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('heatmap_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('norm_x', sa.Float(), nullable=False),
    sa.Column('norm_y', sa.Float(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hour_bucket', sa.Integer(), nullable=True),
    sa.Column('day_bucket', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heatmap_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heatmap_points_timestamp'), ['timestamp'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('clip_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clip_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('suspicion_score_at_capture', sa.Float(), nullable=True),
    sa.Column('is_alert_media', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_timestamp'), ['timestamp'], unique=False)

    op.create_table('suspicion_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suspicion_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suspicion_scores_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suspicion_scores_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspicion_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suspicion_scores_timestamp'))
        batch_op.drop_index(batch_op.f('ix_suspicion_scores_person_id'))

    op.drop_table('suspicion_scores')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_timestamp'))
        batch_op.drop_index(batch_op.f('ix_media_person_id'))

    op.drop_table('media')
    with op.batch_alter_table('heatmap_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heatmap_points_timestamp'))

    op.drop_table('heatmap_points')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_person_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alerts_session_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_person_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('repeat_visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repeat_visitors_cluster_id'))

    op.drop_table('repeat_visitors')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_session_id'))
        batch_op.drop_index(batch_op.f('ix_persons_appearance_cluster_id'))

    op.drop_table('persons')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
